# Neural Network

In [1]:
import torch

## Matrix Multiplication

In [2]:
# Batch Matrix Multiplication
# z = torch.bmm(x, y)

In [3]:
x = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
y = torch.FloatTensor([[1, 2],
                       [1, 2]])
x.shape, y.shape

(torch.Size([3, 2]), torch.Size([2, 2]))

In [4]:
z = torch.matmul(x, y)
z.shape

torch.Size([3, 2])

In [6]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4],
                        [5, 6]],
                       [[7, 8],
                        [9, 10],
                        [11, 12]],
                       [[13, 14],
                        [15, 16],
                        [17, 18]]])
y = torch.FloatTensor([[[1, 2, 2],
                        [1, 2, 2]],
                       [[1, 3, 3],
                        [1, 3, 3]],
                       [[1, 4, 4],
                        [1, 4, 4]]])
x.shape, y.shape

(torch.Size([3, 3, 2]), torch.Size([3, 2, 3]))

In [7]:
z = torch.bmm(x, y)
z.shape

torch.Size([3, 3, 3])

## Linear Layer
- Fully-connected Layer

### Raw Linear Layer

In [17]:
W = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
b = torch.FloatTensor([2, 2])

w.shape, b.shape

(torch.Size([3, 2]), torch.Size([2]))

In [18]:
def linear(x, W, b):
    return torch.matmul(x, W) + b

In [19]:
x = torch.FloatTensor([[1, 1, 1],
                       [2, 2, 2],
                       [3, 3, 3],
                       [4, 4, 4]])
x.shape

torch.Size([4, 3])

In [20]:
y = linear(x, W, b)
y, y.shape

(tensor([[11., 14.],
         [20., 26.],
         [29., 38.],
         [38., 50.]]),
 torch.Size([4, 2]))

### nn.Module

In [22]:
import torch.nn as nn

In [24]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
        
        
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch_size, output_dim)
        
        return y

In [28]:
linear = MyLinear(3, 2)

y = linear(x)

y.shape

torch.Size([4, 2])

In [33]:
## 학습가능한 W가 없기 때문에 출력 없음
for p in linear.parameters():
    print(p)

### nn.Parameter

In [34]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        # nn.Parameter로 감싸주어야 학습되는 매개변수
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
        
        
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch_size, output_dim)
        
        return y

In [35]:
linear = MyLinear(3, 2)

# linear.forward() 호출 필요 없는이유, torch가 알아서 설정해놓음. 이렇게 사용하는 것이 효율적
y = linear(x)

y.shape

torch.Size([4, 2])

In [36]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[2.6625e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]], requires_grad=True)
Parameter containing:
tensor([0.0000e+00, 2.5244e-29], requires_grad=True)


### nn.Linear

In [39]:
linear = nn.Linear(3, 2)

y = linear(x)

y.shape

torch.Size([4, 2])

In [40]:
# W.T로 계산하여 (3, 2)로 실제 계산 |W| = (2, 3)
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[-0.4214, -0.5501,  0.2533],
        [-0.3915, -0.4738, -0.1952]], requires_grad=True)
Parameter containing:
tensor([-0.2404, -0.3797], requires_grad=True)


In [41]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        # nn.Parameter로 감싸주어야 학습되는 매개변수
        self.linear = nn.Linear(input_dim, output_dim)
        
        
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = self.linear(x)
        # |y| = (batch_size, output_dim)
        
        return y

In [42]:
linear = MyLinear(3, 2)

y = linear(x)

y.shape

torch.Size([4, 2])

In [43]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.4549,  0.1411,  0.3290],
        [-0.2423, -0.3423, -0.2456]], requires_grad=True)
Parameter containing:
tensor([0.2862, 0.2690], requires_grad=True)
