In [1]:
import torch

## Basic

In [9]:
# 32bit
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [11]:
# int64
# index와 같은 값 담을 때 사용
lt = torch.LongTensor([[1, 2],
                      [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [12]:
# 0, 1 / True, False
# Boolean Tensor가 있음.
bt = torch.ByteTensor([[1, 0], 
                       [0, 1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [14]:
# Random Values
x = torch.FloatTensor(3, 2, 2)
x

tensor([[[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[2.5223e-44, 1.6255e-43],
         [1.5554e-43, 1.5975e-43]],

        [[1.3873e-43, 1.4574e-43],
         [6.4460e-44, 1.0650e-43]]])

In [15]:
import numpy as np

x = np.array([[1, 2],
              [3, 4]])
x, type(x)

(array([[1, 2],
        [3, 4]]),
 numpy.ndarray)

In [16]:
x = torch.from_numpy(x)
x, type(x)

(tensor([[1, 2],
         [3, 4]]),
 torch.Tensor)

In [17]:
x = x.numpy()
x, type(x)

(array([[1, 2],
        [3, 4]]),
 numpy.ndarray)

In [18]:
# .method() -> 해당 타입으로 변경
ft, ft.long()

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[1, 2],
         [3, 4]]))

In [20]:
lt, lt.float()

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1., 2.],
         [3., 4.]]))

In [22]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [10, 11]]])
x.size(), x.shape

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]))

In [25]:
x.dim(), len(x.shape), len(x.size())

(3, 3, 3)

In [30]:
print(x.shape)
print(x.shape[0], x.shape[1], x.shape[2])

torch.Size([3, 2, 2])
3 2 2


In [31]:
x.shape[-1]

2

## Operations

In [33]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [34]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [35]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [37]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [38]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [39]:
a == b

tensor([[False,  True],
        [ True, False]])

In [40]:
a != b

tensor([[ True, False],
        [False,  True]])

In [41]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations

In [43]:
print(a)
print(a.mul(b)) # == a * b
print()
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])

tensor([[1., 2.],
        [3., 4.]])


In [44]:
print(a)
print(a.mul_(b))
print()
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])

tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean(Dimension Reducing Operations)

In [46]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [49]:
# dim : 차원 축소하여 계산
x.sum(), x.sum(dim=0), x.sum(dim=-1)

(tensor(10.), tensor([4., 6.]), tensor([3., 7.]))

In [51]:
x.mean(), x.mean(dim=0), x.mean(dim=-1)

(tensor(2.5000), tensor([2., 3.]), tensor([1.5000, 3.5000]))

## Broadcast in Operations

In [52]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

x.shape, y.shape

(torch.Size([1, 2]), torch.Size([1, 2]))

In [53]:
z = x + y
z, z.shape

(tensor([[ 5., 10.]]), torch.Size([1, 2]))

### Tensor + Scalar

In [55]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1
x.shape

torch.Size([2, 2])

In [56]:
x + y, (x + y).shape

(tensor([[2., 3.],
         [4., 5.]]),
 torch.Size([2, 2]))

### Tensor + Vector

In [59]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3,
                       5])
x.shape, y.shape

(torch.Size([2, 2]), torch.Size([2]))

In [58]:
z = x + y
z, z.shape

(tensor([[ 4.,  7.],
         [ 7., 13.]]),
 torch.Size([2, 2]))

In [63]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3,
                       5])
x.shape, y.shape

(torch.Size([1, 1, 2]), torch.Size([2]))

In [64]:
z = x + y
z, z.shape

(tensor([[[4., 7.]]]), torch.Size([1, 1, 2]))

### Tensor + Tensor

In [65]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])
x.shape, y.shape

(torch.Size([1, 2]), torch.Size([2, 1]))

In [67]:
z = x + y
z, z.shape

(tensor([[4., 5.],
         [6., 7.]]),
 torch.Size([2, 2]))

## Tensor Shaping

In [68]:
x = torch.FloatTensor([[[1, 2],
                       [3, 4]],
                       
                       [[5, 6],
                        [7, 8]],
                      
                       [[9, 10],
                        [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [75]:
print(x.reshape(12))
print(x.reshape(-1))
print(x.reshape(12).shape, x.reshape(-1).shape)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
torch.Size([12]) torch.Size([12])


In [76]:
x.reshape(3, 4), x.reshape(3, -1)

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]))

In [77]:
x.reshape(3, 1, 4), x.reshape(-1, 1, 4)

(tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]),
 tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]))

In [78]:
x.reshape(3, 2, 2, 1)

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])

## Squeeze

In [81]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
x, x.shape

(tensor([[[1., 2.],
          [3., 4.]]]),
 torch.Size([1, 2, 2]))

In [80]:
x.squeeze(), x.squeeze().shape

(tensor([[1., 2.],
         [3., 4.]]),
 torch.Size([2, 2]))

In [82]:
# Dimension Index를 넣으면 해당 dim만 squeeze
x.squeeze(0).shape, x.squeeze(1).shape

(torch.Size([2, 2]), torch.Size([1, 2, 2]))

### Unsqueeze

In [83]:
x = torch.FloatTensor([[1, 2],
                        [3, 4]])
x, x.shape

(tensor([[1., 2.],
         [3., 4.]]),
 torch.Size([2, 2]))

In [85]:
x.unsqueeze(2), x.unsqueeze(2).shape

(tensor([[[1.],
          [2.]],
 
         [[3.],
          [4.]]]),
 torch.Size([2, 2, 1]))

In [86]:
x.unsqueeze(-1), x.unsqueeze(-1).shape

(tensor([[[1.],
          [2.]],
 
         [[3.],
          [4.]]]),
 torch.Size([2, 2, 1]))

In [87]:
x.reshape(2, 2, -1)

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])

## Slicing and Concatenation

### Indexing and Slicing

In [100]:
x = torch.FloatTensor([[[1, 2],
                       [3, 4]],
                      
                       [[5, 6],
                        [7, 8]],
                      
                       [[9, 10],
                        [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [101]:
x[0], x[0, :], x[0, :, :]

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[1., 2.],
         [3., 4.]]),
 tensor([[1., 2.],
         [3., 4.]]))

In [102]:
x[-1], x[-1, :], x[-1, :, :]

(tensor([[ 9., 10.],
         [11., 12.]]),
 tensor([[ 9., 10.],
         [11., 12.]]),
 tensor([[ 9., 10.],
         [11., 12.]]))

In [103]:
x[:, 0, :], x[:, 0, :].shape

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]),
 torch.Size([3, 2]))

In [104]:
x[1:3, :, :], x[:, :1, :], x[:, :-1, :]

(tensor([[[ 5.,  6.],
          [ 7.,  8.]],
 
         [[ 9., 10.],
          [11., 12.]]]),
 tensor([[[ 1.,  2.]],
 
         [[ 5.,  6.]],
 
         [[ 9., 10.]]]),
 tensor([[[ 1.,  2.]],
 
         [[ 5.,  6.]],
 
         [[ 9., 10.]]]))

In [105]:
x[1:3, :, :].shape, x[:, :1, :].shape, x[:, :-1, :].shape

(torch.Size([2, 2, 2]), torch.Size([3, 1, 2]), torch.Size([3, 1, 2]))

### Split

In [118]:
x = torch.FloatTensor(19, 4)
x, s.shape

(tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 6.9500e+13, 1.4013e-45],
         [6.9500e+13, 1.4013e-45, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00

In [122]:
# 0번 dim이 4가 되도록 split
splits = x.split(4, dim=0)

for s in splits :
    print(s.shape)

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([3, 4])


### Chunk

In [123]:
x = torch.FloatTensor(19, 4)
x

tensor([[7.9874e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 6.9500e+13, 1.4013e-45],
        [6.9500e+13, 1.4013e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.000

In [124]:
# 0번 dim을 기준으로 3개로 나눠라 
chunks = x.chunk(3, dim=0)

for c in chunks:
    print(c.shape)

torch.Size([7, 4])
torch.Size([7, 4])
torch.Size([5, 4])


### Index_select

In [125]:
x = torch.FloatTensor([[[1, 1],
                        [2, 2]],
                       [[3, 3],
                        [4, 4]],
                       [[5, 5],
                        [6, 6]]])
indice = torch.LongTensor([2, 1])

x.shape

torch.Size([3, 2, 2])

In [126]:
# indice = [2, 1]
# index_select -> dim 0번의 [2번 index, 1번 index 값]
y = x.index_select(dim=0, index=indice)

y, y.size

(tensor([[[5., 5.],
          [6., 6.]],
 
         [[3., 3.],
          [4., 4.]]]),
 <function Tensor.size>)

In [127]:
indice2 = torch.LongTensor([2, 0])

y = x.index_select(dim=0, index=indice2)

y, y.size

(tensor([[[5., 5.],
          [6., 6.]],
 
         [[1., 1.],
          [2., 2.]]]),
 <function Tensor.size>)

### Concat

In [128]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])
x.shape, y.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [132]:
z = torch.cat([x, y], dim=-1)
z, z.shape

(tensor([[ 1.,  2.,  3., 10., 11., 12.],
         [ 4.,  5.,  6., 13., 14., 15.],
         [ 7.,  8.,  9., 16., 17., 18.]]),
 torch.Size([3, 6]))

In [133]:
z = torch.cat([x, y], dim=0)
z, z.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]),
 torch.Size([6, 3]))

### Stack

In [134]:
x, y

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]))

In [135]:
z = torch.stack([x, y])
z, z.shape

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]),
 torch.Size([2, 3, 3]))

In [137]:
z = torch.stack([x, y], dim=1)
z, z.shape

(tensor([[[ 1.,  2.,  3.],
          [10., 11., 12.]],
 
         [[ 4.,  5.,  6.],
          [13., 14., 15.]],
 
         [[ 7.,  8.,  9.],
          [16., 17., 18.]]]),
 torch.Size([3, 2, 3]))

In [136]:
z = torch.stack([x, y], dim=-1)
z, z.shape

(tensor([[[ 1., 10.],
          [ 2., 11.],
          [ 3., 12.]],
 
         [[ 4., 13.],
          [ 5., 14.],
          [ 6., 15.]],
 
         [[ 7., 16.],
          [ 8., 17.],
          [ 9., 18.]]]),
 torch.Size([3, 3, 2]))

In [138]:
z = torch.stack([x, y], dim=3)
z, z.shape

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

### Stack by unsing 'cat'

In [139]:
z = torch.stack([x, y])
zz = torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)
z, zz

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]),
 tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]))

### Merge results from iterations

In [140]:
result = []

for i in range(5):
    x = torch.FloatTensor(2, 2)
    result += [x]

result = torch.stack(result)
result.shape

torch.Size([5, 2, 2])

## +@

### Expand

In [144]:
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])
x.shape

torch.Size([2, 1, 2])

In [145]:
y = x.expand(*[2, 3, 2]) # = x.expand(2, 3, 2)
y, y.shape

(tensor([[[1., 2.],
          [1., 2.],
          [1., 2.]],
 
         [[3., 4.],
          [3., 4.],
          [3., 4.]]]),
 torch.Size([2, 3, 2]))

In [149]:
y = torch.cat([x, x, x], dim=1)
y, y.shape

(tensor([[[1., 2.],
          [1., 2.],
          [1., 2.]],
 
         [[3., 4.],
          [3., 4.],
          [3., 4.]]]),
 torch.Size([2, 3, 2]))

### Randperm

In [154]:
x = torch.randperm(10)
x, x.shape

(tensor([0, 5, 7, 4, 1, 3, 9, 8, 6, 2]), torch.Size([10]))

In [161]:
x = torch.randperm(3**3 * 2)
print(x)
print(x.shape)
x.reshape(3, 3, 2, -1).shape

tensor([41, 46, 48, 47, 52, 19,  0, 36, 14,  9, 53, 16, 42, 24, 30, 34,  7, 12,
         8, 31, 38, 45,  1,  6,  2,  3, 39, 28, 10, 27, 20, 43, 33, 29, 50, 32,
        23, 35, 44, 51, 49, 25, 15, 40, 17,  4, 22, 26, 18, 11, 21,  5, 37, 13])
torch.Size([54])


torch.Size([3, 3, 2, 3])

### Argmax

In [162]:
x = torch.randperm(3**3).reshape(3, 3, -1)

x, x.shape

(tensor([[[ 6, 11,  3],
          [ 7,  2,  0],
          [14, 25,  5]],
 
         [[15, 21, 10],
          [12, 20,  1],
          [13, 24, 22]],
 
         [[19,  4,  9],
          [23, 16, 26],
          [17,  8, 18]]]),
 torch.Size([3, 3, 3]))

In [163]:
y = x.argmax(dim=-1)
y, y.shape

(tensor([[1, 0, 1],
         [1, 1, 1],
         [0, 2, 2]]),
 torch.Size([3, 3]))

### topk

In [164]:
# 가장 큰 value와 index를 return
# k: 뽑아낼 갯수, dim: 차원
values, indices = torch.topk(x, k=1, dim=-1)

values.shape, indices.shape # (3, 3, 1) <= k=1이기 때문에

(torch.Size([3, 3, 1]), torch.Size([3, 3, 1]))

In [169]:
values.squeeze(-1), indices.squeeze(-1) # <= argmax와 동일하게 나옴(k=1이기 때문에)

(tensor([[11,  7, 25],
         [21, 20, 24],
         [19, 26, 18]]),
 tensor([[1, 0, 1],
         [1, 1, 1],
         [0, 2, 2]]))

In [170]:
x.argmax(dim=-1) == indices.squeeze(-1)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [172]:
values, indices = torch.topk(x, k=2, dim=-1)

print(values)
values.shape, indices.shape

tensor([[[11,  6],
         [ 7,  2],
         [25, 14]],

        [[21, 15],
         [20, 12],
         [24, 22]],

        [[19,  9],
         [26, 23],
         [18, 17]]])


(torch.Size([3, 3, 2]), torch.Size([3, 3, 2]))

In [175]:
x.argmax(dim=-1) == indices[:, :, 0]

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### Sort by using topk

In [181]:
x

tensor([[[ 6, 11,  3],
         [ 7,  2,  0],
         [14, 25,  5]],

        [[15, 21, 10],
         [12, 20,  1],
         [13, 24, 22]],

        [[19,  4,  9],
         [23, 16, 26],
         [17,  8, 18]]])

In [180]:
# k를 특정 dim의 size만큼 줌으로써 sort
target_dim = -1
values, indices = torch.topk(x,
                            k=x.size(target_dim),
                            largest=True) # largest를 통해 오름 내림차순 정렬
values 

tensor([[[11,  6,  3],
         [ 7,  2,  0],
         [25, 14,  5]],

        [[21, 15, 10],
         [20, 12,  1],
         [24, 22, 13]],

        [[19,  9,  4],
         [26, 23, 16],
         [18, 17,  8]]])

In [183]:
k = 3
values, indices = torch.sort(x, dim=-1, descending=True)
values, indices = values[:, :, :k], indices[:, :, :k]

values.squeeze(-1), indices.squeeze(-1)

(tensor([[[11,  6,  3],
          [ 7,  2,  0],
          [25, 14,  5]],
 
         [[21, 15, 10],
          [20, 12,  1],
          [24, 22, 13]],
 
         [[19,  9,  4],
          [26, 23, 16],
          [18, 17,  8]]]),
 tensor([[[1, 0, 2],
          [0, 1, 2],
          [1, 0, 2]],
 
         [[1, 0, 2],
          [1, 0, 2],
          [1, 2, 0]],
 
         [[0, 2, 1],
          [2, 0, 1],
          [2, 0, 1]]]))

In [184]:
k = 1
values, indices = torch.sort(x, dim=-1, descending=True)
values, indices = values[:, :, :k], indices[:, :, :k]

values.squeeze(-1), indices.squeeze(-1)

(tensor([[11,  7, 25],
         [21, 20, 24],
         [19, 26, 18]]),
 tensor([[1, 0, 1],
         [1, 1, 1],
         [0, 2, 2]]))

In [185]:
## pytorch 1.6 기준 topk와 sort의 속도가 매번 다름(CPU, GPU)

### Masked_fill

In [186]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

x, x.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]),
 torch.Size([3, 3]))

In [187]:
mask = x > 4
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [188]:
y = x.masked_fill(mask, value=-1)
y

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

### Ones and Zeros

In [189]:
torch.ones(2, 3), torch.zeros(2, 3)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [190]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
x.shape

torch.Size([2, 3])

In [191]:
torch.ones_like(x), torch.zeros_like(x)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))